### ISSUE TITLE
Questions about INbreast ground truth

### ISSUE THREAD

**Issue by taijizhao** [riblidezso/frcnn_cad#1]
Dear Dezso, 
Congratulations for the excellent work! It's amazing that your approach achieved so good results on DM challenge even without using the training data!
I have some questions about your paper and look for help. 
First, what did you use as the ground truth for the INbreast data? I only found Bi-Rads scores in the meta data file, but it's not the real Benign/Malignant ground truth.  In the INbreast paper it wrote: "A biopsy result for BI RADS 3, 4, 5, and 6 cases is also displayed whenever performed. The remaining cases were considered benign and therefore a biopsy was therefore not performed. Consequently, a biopsy was performed on 56 cases, of which 11 were found to be benign and the remaining 45 were malignant."  However, I fail to identify which are those 45 malignant cases. 
Second, the ROC curve on INbreast in your paper, was it measured per-image level or per-breast level? For example did you fuse the CC and MLO detection scores? 
Finally, according to your paper and your achievement in DM challenge, faster-rcnn works amazingly well. However, I think faster rcnn actually ignores roi size information and changes the aspect ration because of the roi-pooling. These information might be important for cancer classification. Do you think there is a chance to do something in this aspect?
Thank you very much and looking for your reply!
Xuran

**Comment by riblidezso** [comment]
Hi,

Thanks for the interest and sorry for the late answer.

About Inbreast ground truth:
Look at the second sheet of the inbreast excel file, where pathological findings can be found (in portuguese). Altough there is no unique id, the cases can be matched with the ones on the first sheet based on birads scores, and dates, at least to the extent of malignant-benign. Some of the cases remain ambiguous, I have excluded these, as mentioned in the paper. 

The ROC curve is done on breast level, i think this is stated in the paper, but it will be more emphasized in the next revision.

About the possible improvements. You are right, the approach ignores many aspects human doctors would consider. Just to name a few more apart from size and aspect ratios: position, global context, breast comparisions, comparison with previous images, comparison of MLO-CC views. It really is amazing that the system just works so well, even though it only relies on it's (extremely powerful) pattern matching capability. Probably there is room for improvement.

I hope things are more clear now, good luck with your work on the topic!

**Comment by xuranzhao711** [comment]
@riblidezso 
Thank you very much!

**Comment by taijizhao** [comment]
@riblidezso 
Thank you very much for your detailed explanation! That helped me a lot.

**Comment by jeccavy** [comment]
I hope you can address the GT question again. Your answer:
About Inbreast ground truth:
Look at the second sheet of the inbreast excel file, where pathological findings can be found (in portuguese). Altough there is no unique id, the cases can be matched with the ones on the first sheet based on birads scores, and dates, at least to the extent of malignant-benign.

does not help, the dates in the second sheet are full dates, while the dates in the first sheet are year and semester, so for example a birads of 2 for a date 20090826 has 60 matches in the first sheet. Am I missing something?
